import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import { Toaster } from '@/components/ui/sonner';

const recursive = Recursive({
  variable: '--font-recursive',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TwinifyAPI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recursive.className} min-h-[calc(100vh-1px) bg-[#EFF6FD] antialiased flex flex-col text-[#111827]`}
      >
        <main className="relative flex flex-1 flex-col">
          <Navbar />
          {children}
        </main>
        <Toaster richColors />
      </body>
    </html>
  );
}
